#!/usr/bin/env ruby
require_relative '../lib/katakata_irb'
unless ARGV.delete '--without-patch'
  require_relative '../lib/katakata_irb/reline_patch'
  KatakataIrb::RelinePatch.require_patched_reline
  require 'katakata_irb/ruby_lex_patch'
  KatakataIrb::RubyLexPatch.patch_to_ruby_lex
end
KatakataIrb.log_output = STDERR if ARGV.delete '--debug-output'
KatakataIrb.repl
